name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build GDExtension
    uses: ./.github/workflows/build.yml
    with:
      concurrency-group: ${{ github.event.release.tag_name }}
      float-precision: double

  archive:
    needs: build
    name: Upload Release Archive
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: addons/${{ needs.build.outputs.artifact-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We only need the .git folder, but it's not supported yet (https://github.com/actions/checkout/issues/603).
          # This minimises what's checked out.
          sparse-checkout: |
            .github
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: ${{ github.workspace }}/${{ env.ARTIFACT_PATH }}
      - name: Create & Upload Archive
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHIVE_NAME: ${{ needs.build.outputs.artifact-name }}-${{ github.event.release.tag_name }}.tar.gz
        run: |
          echo "Creating $ARCHIVE_NAME from ${{ env.ARTIFACT_PATH }}"
          tar -cvf $ARCHIVE_NAME ${{ env.ARTIFACT_PATH }}
          echo "Uploading $ARCHIVE_NAME to release ${{ github.event.release.tag_name }}"
          gh release upload ${{ github.event.release.tag_name }} $ARCHIVE_NAME
